global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'evidflow-services'
    static_configs:
      - targets: 
        - 'gateway:4000'
        - 'auth-service:4001'
        - 'org-service:4002'
        - 'beneficiaries-service:4003'
        - 'meal-service:4004'
        - 'payments-service:4005'
        - 'reports-service:4006'
        - 'analytics-service:4007'
        - 'ai-service:4008'
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
